### ISSUE TITLE
AttributeError: ToonBase instance has no attribute 'settings'

### ISSUE THREAD

**Issue by 2Epik4u** [Benjamin8693/Toontown-Magic-Word-Manager#1]
When I pick my toon, the game crashes and I get  https://pastebin.com/raw/PSHv0utt

**Comment by ooowoothevirtualhowler** [comment]
I'm a bit late on this but you might have to replace `base.settings.getInt()` with a different method call for the Settings class in your source. The definition of the Settings class here is based on Offline as this is based on the Toontown Offline Magic Word Manager.

**Comment by 2Epik4u** [comment]
lol i use school house now
